### ISSUE TITLE
Log File Central

### ISSUE THREAD

**Issue by GerhardABSA** [CameronABSA/Activity-Tracker-AT-#14]
I think we need to change the config files of all the different components to point to a single location no matter what application it is we incorporate into the system. Even if this means we have a variable {system Variable} we use for this. It will help a lot in the debug and management of the environment. Else we need to troll through a multitude of log files on different environments to find the issues. IF we do this from the start we will be able to solve issues quickly. So I think we need to agree on a location like C:\ApplicaitonLogs\{Applicaiton}\{Logfile.txt}
I just find it already difficult with the log files all over to try and manage the errors within the environment.

**Comment by CameronABSA** [comment]
From what I have seen you've already completed this on your server? locking this for now
