### ISSUE TITLE
DP Workflow Re Assign

### ISSUE THREAD

**Issue by GerhardABSA** [CameronABSA/Activity-Tracker-AT-#58]
Hi there we would like to be able to re assign the workflow to another user in the DP team.
(I think there should be a DP specialist team thus to a member of that team)

**Comment by CameronABSA** [comment]
At the moment the user can just unclaim the item which will automatically go into the unclaimed bucket for another user to claim but I can build in a function to re-assign it to a specific person without having to go through this.

**Comment by CameronABSA** [comment]
Building this as part of another option
